# Generated by Django 4.0.2 on 2022-02-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Career Name', max_length=50)),
                ('owned_by', models.CharField(help_text='Career Name', max_length=50)),
                ('project_value', models.CharField(max_length=1000)),
                ('scope', models.CharField(max_length=1000)),
                ('role', models.CharField(max_length=1000)),
                ('ongoing', models.BooleanField()),
            ],
        ),
    ]
