# Generated by Django 4.0.2 on 2022-02-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProectDetails',
            new_name='ProjectDetails',
        ),
    ]
