# Generated by Django 4.0.2 on 2022-02-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_phone_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
    ]
