# Generated by Django 4.0.2 on 2022-02-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('home', '0003_alter_jobapplication_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='career',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='career.careers'),
            preserve_default=False,
        ),
    ]
